version: "2.4"

services:
  nginx:
    build:
      args:
        NGINX_IMAGE: nginx:1.19-alpine
      context: .docker/nginx
      dockerfile: Dockerfile
    depends_on:
      php-fpm:
        condition: service_healthy
    healthcheck:
      interval: 5s
      test:
        - CMD
        - curl
        - --fail
        - http://localhost/healthz
      start_period: 3s
    ports:
      - 8080:80
    volumes:
      - ./var/log/nginx:/var/log/nginx:delegated
      - .:/var/www/app:ro,cached

  php:
    build:
      args:
        PHP_IMAGE: php:7.4-cli-alpine3.11
      context: .docker/php
      dockerfile: cli/Dockerfile
    environment:
      APP_ENV: dev
      APP_SECRET: 08cc42627da90a29d9d87a7bc76c4ce8
      OPCACHE_ENABLE: ${OPCACHE_ENABLE:-Off}
      PCOV_ENABLE: ${PCOV_ENABLE:-On}
      XDEBUG_ENABLE: ${XDEBUG_ENABLE:-Off}
    volumes:
      - composer:/composer/cache/files:delegated
      - ./:/var/www/app:cached
      - ./var:/var/www/app/var:delegated
      - ./var/log/php:/var/log/php:delegated

  php-fpm:
    build:
      args:
        PHP_IMAGE: php:7.4-fpm-alpine3.11
      context: .docker/php
      dockerfile: fpm/Dockerfile
    environment:
      APP_ENV: dev
      APP_SECRET: 08cc42627da90a29d9d87a7bc76c4ce8
      OPCACHE_ENABLE: ${OPCACHE_ENABLE:-Off}
      XDEBUG_ENABLE: ${XDEBUG_ENABLE:-Off}
    healthcheck:
      interval: 5s
      test:
        - CMD
        - php-fpm-healthcheck
    volumes:
      - composer:/composer/cache/files:delegated
      - ./:/var/www/app:cached
      - ./var:/var/www/app/var:delegated
      - ./var/log/php:/var/log/php:delegated

volumes:
  composer:
