services:
    _defaults:
        autowire: true
        autoconfigure: true

    MaSpeng\PhpCiSandbox\:
        resource: ../src/*
        exclude: ../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}

    MaSpeng\PhpCiSandbox\Controller\:
        resource: ../src/Controller
        tags:
          - controller.service_arguments
